name: zola-akasolace
version: 0.21.0
summary: Testing app for zola
description: |
  Testing app for zola
license: MIT

base: core22
grade: stable
confinement: strict

parts:
  zola:
    plugin: rust
    rust-channel: stable
    source: https://github.com/akasolace/zola.git
    source-tag: v0.21.0
    build-packages:
      - build-essential
      - cmake
      - pkg-config
      - libssl-dev

apps:
  zola:
    command: bin/zola
    plugs:
      - home
      - network
      - network-bind
      - removable-media